server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8081

spring:
  main:
    allow-circular-references: true

  datasource:
    password: ghtq345
    host: localhost
    port: 5432
    username: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      connection-timeout: 300000
    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/druglist

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect:
        format_sql: true
        use_sql_comments: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect